### ISSUE TITLE
Undo can freeze up the app...

### ISSUE THREAD

**Issue by gcasa** [gnustep/apps-projectcenter#24]
Steps to reproduce:

1. Open a project
2. Open a file, possibly AppController.m/h
3. Copy a line vie the main menu
4. Paste it via the main menu
5. in the main menu, click Undo.

Result: Application may freeze
Expected: Changes should be undone

Comments:  Not sure what is happening here, but I suspect the array or list of events for undo have a cycle of some sort.

**Comment by svgol** [comment]
It seems @rmottola fixed the cause of this issue in the libs-gui #5e837b6

**Comment by gcasa** [comment]
Tested and confirmed.  Thanks @rmottola
